-- 夫妻聊天器 Supabase 数据库结构
-- 使用方式：进入 Supabase Dashboard → SQL Editor → New query → 粘贴执行

-- 创建消息表
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender TEXT NOT NULL CHECK (sender IN ('老婆', '老公')),
  content TEXT NOT NULL,
  time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 启用行级安全策略（RLS）
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 允许匿名用户读取所有消息（适合夫妻两人共用，无需登录）
CREATE POLICY "Allow anonymous read"
ON messages
FOR SELECT
TO anon
USING (true);

-- 允许匿名用户插入消息
CREATE POLICY "Allow anonymous insert"
ON messages
FOR INSERT
TO anon
WITH CHECK (true);
